# Generated by Django 4.0.4 on 2022-05-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='client id')),
                ('secret_key', models.CharField(max_length=255, verbose_name='secret key')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='access token')),
                ('expires_in', models.IntegerField(blank=True, null=True, verbose_name='expires in')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='refresh token')),
                ('token_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='token type')),
                ('channel_id', models.IntegerField(blank=True, null=True, verbose_name='channel id')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('app_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='user token')),
            ],
            options={
                'verbose_name': 'account settings',
                'verbose_name_plural': 'accounts settings',
            },
        ),
        migrations.CreateModel(
            name='BanableUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_verbose', models.CharField(db_index=True, max_length=255, verbose_name='readable username')),
            ],
            options={
                'verbose_name': 'bannable user',
                'verbose_name_plural': 'bannable users',
            },
        ),
        migrations.CreateModel(
            name='BannableUserVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, verbose_name='username variant')),
                ('bannable_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='banhammer.banableuser')),
            ],
            options={
                'verbose_name': 'bannable user variant',
                'verbose_name_plural': 'bannable user variants',
                'ordering': ['username'],
            },
        ),
    ]
